# Generated by Django 5.1.1 on 2024-11-16 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedomeapp', '0002_remove_related_movies_relationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Adult', 'Adult'), ('Animation', 'Animation'), ('Comedy', 'Comedy'), ('Crimes', 'Crimes'), ('Documentary', 'Documentary')], max_length=200, verbose_name='movies genre'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='fam',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Documentary', 'documentary'), ('General', 'General')], default='General', max_length=200, verbose_name='the image types select'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_types',
            field=models.CharField(choices=[('Chinese movies', 'Chinese movies'), ('Philipine movies', 'Philipine movies'), ('Korean drama', 'Korean drama'), ('Indian movies', 'Indian movies'), ('Nollywood', 'Nollywood'), ('Hollywood', 'Hollywood'), ('Animation movies', 'Animation movies'), ('Japanese movies', 'Japanese movies'), ('American movie', 'American movies')], default='American movies', max_length=200, verbose_name='select the categories to clasifile the movie'),
        ),
        migrations.AlterField(
            model_name='series',
            name='Genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Adult', 'Adult'), ('Animation', 'Animation'), ('Crimes', 'Crimes'), ('Comedy', 'Comedy'), ('Documentary', 'Documentary')], max_length=200, verbose_name='series genre'),
        ),
        migrations.AlterField(
            model_name='series',
            name='fam',
            field=models.CharField(choices=[('trending', 'trending'), ('Documentary', 'documentary'), ('General', 'General')], default='General', max_length=200, verbose_name='the series types select'),
        ),
        migrations.AlterField(
            model_name='series',
            name='frame',
            field=models.ImageField(upload_to='series_pics', verbose_name='frame cover image of the series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='meta',
            field=models.TextField(verbose_name='meta discrption for the series page somthing that discribes the series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='reales',
            field=models.IntegerField(default=2020, null=True, verbose_name='series reales date'),
        ),
        migrations.AlterField(
            model_name='series',
            name='s_title',
            field=models.TextField(verbose_name='the search title for this series can include the series name and series discription or bio'),
        ),
        migrations.AlterField(
            model_name='series',
            name='search_str',
            field=models.TextField(blank=True, null=True, verbose_name='series search string this will auto generate'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_file',
            field=models.FileField(unique=True, upload_to='seriesfiles', verbose_name='file of the seies, if series is seasonal please add the part one'),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug_name',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='series special slug do not add'),
        ),
        migrations.CreateModel(
            name='seasonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='series/ movie name')),
                ('s_title', models.TextField(verbose_name='the search title for this series / movie can include the movie name and series discription or bio')),
                ('title', models.TextField(verbose_name='a simple page title')),
                ('meta', models.TextField(verbose_name='meta discrption for the series page somthing that discribes the movie')),
                ('discription', models.TextField(verbose_name='movies discription about the movie / series ')),
                ('views', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='number of views and visits, pls do not add this this will automatically add it self')),
                ('posted_by', models.CharField(max_length=200, verbose_name='add name of staff posting this vidie')),
                ('duration', models.CharField(max_length=50, verbose_name='mins of movie length the duration')),
                ('reales', models.IntegerField(default=2020, null=True, verbose_name='movies /series reales date')),
                ('pub_date', models.DateTimeField(verbose_name='published date')),
                ('frame', models.ImageField(upload_to='series_pics', verbose_name='frame cover image of the series / movies')),
                ('file', models.FileField(unique=True, upload_to='seriesfiles', verbose_name=' add file by spcifing the movie and also the one its inheriting from u can add multiple files')),
                ('is_edited', models.BooleanField(default=False, verbose_name='do not add this its for the file and image editions')),
                ('is_published', models.BooleanField(default=False, verbose_name='if movie is publised')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='movie_thumbnails', verbose_name='thumbnail do not add this ')),
                ('slug_name', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='movie / series special slug do not add')),
                ('search_str', models.TextField(blank=True, null=True, verbose_name='movies / series search string this will auto generate')),
                ('spec_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='do not add it will auto generate, movies string')),
                ('verifed', models.BooleanField(default=False, verbose_name='do not click this verification')),
                ('main_movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moviedomeapp.movies')),
                ('main_series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moviedomeapp.series')),
            ],
        ),
    ]
