# Generated by Django 5.1.1 on 2024-11-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedomeapp', '0003_alter_movies_genre_alter_movies_fam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonal',
            name='main_series',
        ),
        migrations.AlterField(
            model_name='seasonal',
            name='main_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moviedomeapp.movies'),
        ),
    ]
